@apimName = aisesbpo7ljlwnuiyjri-apim
@subscriptionKey = 527c041475474b47bf166ce1fc3eab20

### Customer API - Create
POST https://{{apimName}}.azure-api.net/customer/create
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{subscriptionKey}}

{
    "firstName": "Kathleen",
    "lastName": "Hernandez",
    "status": 0
}

### Customer API - Delete
DELETE https://{{apimName}}.azure-api.net/customer/delete
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{subscriptionKey}}

{
    "id": 1
}

### Customer API - Update
PATCH https://{{apimName}}.azure-api.net/customer/update
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{subscriptionKey}}

{
    "id": 1,
    "firstName": "Kathleen",
    "lastName": "Hernandez",
    "status": 0
}

### Customer API - Get, filter on id
GET https://{{apimName}}.azure-api.net/customer/get?id=1
Ocp-Apim-Subscription-Key: {{subscriptionKey}}

### Customer API - Get Updates
GET https://{{apimName}}.azure-api.net/customer/get-updates
Ocp-Apim-Subscription-Key: {{subscriptionKey}}